spring.application.name=auth_system


spring.datasource.url=jdbc:mysql://localhost:3306/authSystem
spring.datasource.username=root
spring.datasource.password=Root@312


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# jwt.secret=fQd9kX8m7b5jXK9+4AbCdEfGhIjKlMnOpQrStUvWxYz0123456789abcDEFghIJKL

spring.security.oauth2.client.registration.google.client-id=1086741822975-0fd78jaffmmjaf9mtslqpn6ng83i34u6.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email
